// ── TRANSLATIONS ─────────────────────────────────────────────────────────────
const T = {
    ko: {
        langNative: '한국어',
        siteSubtitle: '지속가능발전목표 쇼핑몰',
        guideTitle: '사용법',
        guideSteps: [
            { label: '목표 선택', desc: '관심 있는 SDGs 목표를 골라 장바구니에 담으세요.' },
            { label: '계획 수립', desc: '이름·학교 정보를 입력하고 실천 방법을 선택하세요.' },
            { label: '영수증 발급', desc: '완료 후 영수증을 다운로드하거나 인쇄하세요.' },
        ],
        carousel: [
            { title: 'SDGs 애니메이션', desc: '쉽고 재미있게 SDGs를 이해해보세요', btn: '▶ 영상 보기' },
            { title: 'SDGs란 무엇인가요?', desc: '지속가능발전목표의 의미와 역사를 알아보세요', btn: '자세히 살펴보기 →' },
            { title: 'SDGs 17개 목표 알아보기', desc: '17개 목표와 세부목표를 사전처럼 살펴보세요', btn: '목표 살펴보기 →' },
        ],
        sectionTitle: '판매중인 상품', sectionSubtitle: 'SDGs 지속가능발전목표 17개',
        selectBtn: '🛒 선택하기', selectedBtn: '🛒 선택됨', quickBtn: '⚡ 바로실천',
        goalLabel: '목표',
        cartTitle: '선택한 SDGs 목표', backBtn: '돌아가기',
        cartEmpty: '선택한 목표가 없습니다.', goSelectBtn: '목표 선택하러 가기',
        totalGoals: '총 선택한 목표:', toCheckoutBtn: '실천계획 입력하기',
        selectedGoals: '선택한 목표:', toCheckoutShort: '실천계획 세우기',
        checkoutTitle: '실천계획 세우기', backToCart: '장바구니로',
        ordererInfo: '주문자 정보',
        nameRequired: '이름 *', namePlaceholder: '이름을 입력하세요',
        schoolRequired: '학교명 *', schoolPlaceholder: '학교명을 입력하세요',
        gradeRequired: '학년 *', gradeSelect: '학년 선택', gradeOption: n => `${n}학년`,
        classLabel: '반', classPlaceholder: '반을 입력하세요',
        deliveryInfo: '배송 정보(선택)', deliveryAddress: '배송지 주소',
        deliveryAddressPlaceholder: '배송지를 입력하세요', deliveryMemo: '배송 메모(선택)',
        deliveryMemos: ['빠른 배송을 원해요','문 앞에 놓아주세요','실천하지 않을시 알람주세요','부재시 친구에게 맡겨주세요'],
        orderItems: '주문상품 정보', paymentMethod: '결제수단 선택(실천방식)',
        paymentMethods: ['🤔 생각하기','💝 공감하기','🚀 행동하기'],
        paymentValues: ['think','empathize','action'],
        actionPlanTitle: '실천계획 입력', planMethodLabel: '실천계획 방법 선택',
        planMethods: ['글로 작성','그림으로 작성','글과 그림 모두'],
        planValues: ['text','drawing','both'],
        myPlanLabel: '나의 실천계획',
        planPlaceholder: '선택한 SDGs 목표를 위해 어떤 실천을 할 것인지 구체적으로 작성해보세요.',
        drawingLabel: '그림으로 실천계획 그리기',
        clearCanvas: '지우기', colorLabel: '색상:', sizeLabel: '굵기:',
        cancelBtn: '취소', submitBtn: '구매하기',
        errorPayment: '결제수단을 최소 1개 이상 선택해주세요.',
        receiptTitle: '실천 영수증', downloadBtn: '📥 영수증 다운로드',
        printBtn: '🖨️ 인쇄하기', completeBtn: '완료',
        receiptSubtitle: '실천 영수증', receiptOrdererInfo: '주문자 정보',
        receiptName: '이름:', receiptSchool: '학교:', receiptGrade: '학년/반:',
        receiptGoals: '선택한 SDGs 목표', receiptTotalGoals: '총 목표 수:',
        receiptPlanTitle: '나의 실천계획', receiptDrawingTitle: '그림으로 표현한 실천계획',
        receiptFooter: '이 영수증은 여러분의 지속가능발전목표 실천 의지를 나타내는 소중한 증명서입니다.',
        receiptFooter2: '함께 만들어가는 더 나은 세상! 🌍',
        completionTitle: '환영합니다!', completionMsg1: 'SDGs 구입을 축하합니다!',
        completionMsg2: '당신의 선택이 지구를 위한 첫걸음이 되었어요.',
        completionMsg3: '작은 실천이 모여 큰 변화를 만들어냅니다.',
        completionMsg4: '함께 만드는 더 나은 세상, 지금 시작해요!',
        homeBtn: '처음으로',
        toastAddTitle: '목표 선택됨', toastAddDesc: t => `"${t}" 목표가 선택되었습니다!`,
        toastError: '오류', toastDownload: '다운로드 완료', toastDownloadDesc: '영수증이 다운로드되었습니다.',
        toastPrint: '인쇄 준비 완료', toastPrintDesc: '인쇄 창이 열렸습니다.',
        toastPrintFail: '인쇄 실패', toastPrintFailDesc: '팝업이 차단되었습니다. 팝업을 허용해주세요.',
        footerCredit: 'created by. 교육뮤지컬 꿈꾸는 치수쌤',
        footerNote: '이 웹페이지는 SDGs 교육을 위한 학습용 사이트로, 실제 결제나 상품 배송은 이루어지지 않습니다.',
        countUnit: '개',
    },
    en: {
        langNative: 'English',
        siteSubtitle: 'SDGs Shopping Mall',
        guideTitle: 'How to Use',
        guideSteps: [
            { label: 'Select Goals', desc: 'Choose SDG goals you care about and add them to your cart.' },
            { label: 'Make a Plan', desc: 'Enter your name, school info, and choose your action method.' },
            { label: 'Get Receipt', desc: 'Download or print your action receipt when done.' },
        ],
        carousel: [
            { title: 'SDGs Animation', desc: 'Understand SDGs in a fun and easy way', btn: '▶ Watch Video' },
            { title: 'What are the SDGs?', desc: 'Learn about the Sustainable Development Goals', btn: 'Learn More →' },
            { title: 'Explore 17 SDG Goals', desc: 'Browse all 17 goals and their targets like a dictionary', btn: 'Explore Goals →' },
        ],
        sectionTitle: 'Available Goals', sectionSubtitle: '17 UN Sustainable Development Goals',
        selectBtn: '🛒 Select', selectedBtn: '🛒 Selected', quickBtn: '⚡ Act Now',
        goalLabel: 'Goal',
        cartTitle: 'Selected SDG Goals', backBtn: 'Go Back',
        cartEmpty: 'No goals selected.', goSelectBtn: 'Select Goals',
        totalGoals: 'Total Goals:', toCheckoutBtn: 'Create Action Plan',
        selectedGoals: 'Selected:', toCheckoutShort: 'Plan Now',
        checkoutTitle: 'Create Action Plan', backToCart: 'Back to Cart',
        ordererInfo: 'Your Information',
        nameRequired: 'Name *', namePlaceholder: 'Enter your name',
        schoolRequired: 'School *', schoolPlaceholder: 'Enter school name',
        gradeRequired: 'Grade *', gradeSelect: 'Select Grade', gradeOption: n => `Grade ${n}`,
        classLabel: 'Class', classPlaceholder: 'Enter your class',
        deliveryInfo: 'Delivery Info (Optional)', deliveryAddress: 'Delivery Address',
        deliveryAddressPlaceholder: 'Enter delivery address', deliveryMemo: 'Delivery Notes (Optional)',
        deliveryMemos: ['Express delivery please','Leave at door','Notify if not practiced','Leave with friend if absent'],
        orderItems: 'Selected Goals', paymentMethod: 'Action Method',
        paymentMethods: ['🤔 Think','💝 Empathize','🚀 Act'],
        paymentValues: ['think','empathize','action'],
        actionPlanTitle: 'Action Plan', planMethodLabel: 'Choose Method',
        planMethods: ['Write','Draw','Both'],
        planValues: ['text','drawing','both'],
        myPlanLabel: 'My Action Plan',
        planPlaceholder: 'Describe specifically what actions you will take for your selected SDG goals.',
        drawingLabel: 'Draw Your Action Plan',
        clearCanvas: 'Clear', colorLabel: 'Color:', sizeLabel: 'Size:',
        cancelBtn: 'Cancel', submitBtn: 'Commit',
        errorPayment: 'Please select at least one action method.',
        receiptTitle: 'Action Receipt', downloadBtn: '📥 Download Receipt',
        printBtn: '🖨️ Print', completeBtn: 'Done',
        receiptSubtitle: 'Action Receipt', receiptOrdererInfo: 'Your Information',
        receiptName: 'Name:', receiptSchool: 'School:', receiptGrade: 'Grade/Class:',
        receiptGoals: 'Selected SDG Goals', receiptTotalGoals: 'Total Goals:',
        receiptPlanTitle: 'My Action Plan', receiptDrawingTitle: 'Action Plan Drawing',
        receiptFooter: 'This receipt is a certificate of your commitment to the Sustainable Development Goals.',
        receiptFooter2: 'Together for a better world! 🌍',
        completionTitle: 'Congratulations!', completionMsg1: 'You have committed to SDGs!',
        completionMsg2: 'Your choice is the first step for our planet.',
        completionMsg3: 'Small actions together make a big difference.',
        completionMsg4: "Let's build a better world together, starting now!",
        homeBtn: 'Back to Home',
        toastAddTitle: 'Goal Selected', toastAddDesc: t => `"${t}" has been added!`,
        toastError: 'Error', toastDownload: 'Downloaded', toastDownloadDesc: 'Receipt downloaded.',
        toastPrint: 'Print Ready', toastPrintDesc: 'Print window opened.',
        toastPrintFail: 'Print Failed', toastPrintFailDesc: 'Popup blocked. Please allow popups.',
        footerCredit: 'created by. Teacher Chisu',
        footerNote: 'This website is for SDGs education only. No actual payments or deliveries are made.',
        countUnit: '',
    },
    ja: {
        langNative: '日本語',
        siteSubtitle: '持続可能な開発目標ショップ',
        guideTitle: '使い方',
        guideSteps: [
            { label: '目標を選ぶ', desc: '興味のあるSDGs目標を選んでカートに追加しましょう。' },
            { label: '計画を立てる', desc: '名前・学校情報を入力し、実践方法を選択してください。' },
            { label: 'レシートを取得', desc: '完成後はレシートをダウンロードまたは印刷してください。' },
        ],
        carousel: [
            { title: 'SDGsアニメーション', desc: 'SDGsを楽しくわかりやすく理解しましょう', btn: '▶ 動画を見る' },
            { title: 'SDGsとは？', desc: '持続可能な開発目標について学びましょう', btn: '詳しく見る →' },
            { title: 'SDGs 17の目標を見る', desc: '17の目標と具体的なターゲットを辞書のように調べましょう', btn: '目標を調べる →' },
        ],
        sectionTitle: '販売中の商品', sectionSubtitle: 'SDGs 持続可能な開発目標 17個',
        selectBtn: '🛒 選択する', selectedBtn: '🛒 選択済み', quickBtn: '⚡ すぐ実践',
        goalLabel: '目標',
        cartTitle: '選択したSDGs目標', backBtn: '戻る',
        cartEmpty: '選択した目標がありません。', goSelectBtn: '目標を選びに行く',
        totalGoals: '合計目標数:', toCheckoutBtn: '実践計画を入力する',
        selectedGoals: '選択済み:', toCheckoutShort: '計画を立てる',
        checkoutTitle: '実践計画を立てる', backToCart: 'カートに戻る',
        ordererInfo: '注文者情報',
        nameRequired: '名前 *', namePlaceholder: '名前を入力してください',
        schoolRequired: '学校名 *', schoolPlaceholder: '学校名を入力してください',
        gradeRequired: '学年 *', gradeSelect: '学年を選択', gradeOption: n => `${n}年生`,
        classLabel: 'クラス', classPlaceholder: 'クラスを入力してください',
        deliveryInfo: '配送情報（任意）', deliveryAddress: '配送先住所',
        deliveryAddressPlaceholder: '配送先を入力してください', deliveryMemo: '配送メモ（任意）',
        deliveryMemos: ['速達配送希望','ドア前に置いてください','実践しない場合は通知','不在時は友人に'],
        orderItems: '注文商品情報', paymentMethod: '決済手段（実践方法）',
        paymentMethods: ['🤔 考える','💝 共感する','🚀 行動する'],
        paymentValues: ['think','empathize','action'],
        actionPlanTitle: '実践計画の入力', planMethodLabel: '実践計画の方法を選択',
        planMethods: ['文章で作成','絵で作成','文章と絵の両方'],
        planValues: ['text','drawing','both'],
        myPlanLabel: '私の実践計画',
        planPlaceholder: '選択したSDGs目標のために、どのような実践をするか具体的に書いてみましょう。',
        drawingLabel: '絵で実践計画を描く',
        clearCanvas: '消去', colorLabel: '色:', sizeLabel: '太さ:',
        cancelBtn: 'キャンセル', submitBtn: '購入する',
        errorPayment: '決済手段を1つ以上選択してください。',
        receiptTitle: '実践レシート', downloadBtn: '📥 レシートをダウンロード',
        printBtn: '🖨️ 印刷する', completeBtn: '完了',
        receiptSubtitle: '実践レシート', receiptOrdererInfo: '注文者情報',
        receiptName: '名前:', receiptSchool: '学校:', receiptGrade: '学年/クラス:',
        receiptGoals: '選択したSDGs目標', receiptTotalGoals: '合計目標数:',
        receiptPlanTitle: '私の実践計画', receiptDrawingTitle: '絵で表した実践計画',
        receiptFooter: 'このレシートはSDGsへの実践意志を示す大切な証明書です。',
        receiptFooter2: '一緒に作るより良い世界！🌍',
        completionTitle: 'おめでとうございます！', completionMsg1: 'SDGsを購入しました！',
        completionMsg2: 'あなたの選択が地球のための第一歩となりました。',
        completionMsg3: '小さな実践が集まって大きな変化を生み出します。',
        completionMsg4: '一緒に作るより良い世界、今始めましょう！',
        homeBtn: 'トップへ',
        toastAddTitle: '目標を選択しました', toastAddDesc: t => `「${t}」が選択されました！`,
        toastError: 'エラー', toastDownload: 'ダウンロード完了', toastDownloadDesc: 'レシートがダウンロードされました。',
        toastPrint: '印刷準備完了', toastPrintDesc: '印刷ウィンドウが開きました。',
        toastPrintFail: '印刷失敗', toastPrintFailDesc: 'ポップアップをブロックしています。許可してください。',
        footerCredit: 'created by. 교육뮤지컬 꿈꾸는 치수쌤',
        footerNote: 'このサイトはSDGs教育用です。実際の決済・配送は行われません。',
        countUnit: '個',
    },
    id: {
        langNative: 'Indonesia',
        siteSubtitle: 'Mall SDGs',
        guideTitle: 'Cara Penggunaan',
        guideSteps: [
            { label: 'Pilih Tujuan', desc: 'Pilih tujuan SDGs yang ingin Anda dukung dan masukkan ke keranjang.' },
            { label: 'Buat Rencana', desc: 'Isi nama, info sekolah, dan pilih metode aksi Anda.' },
            { label: 'Dapatkan Kuitansi', desc: 'Unduh atau cetak kuitansi aksi Anda setelah selesai.' },
        ],
        carousel: [
            { title: 'Animasi SDGs', desc: 'Pahami SDGs dengan cara yang menyenangkan', btn: '▶ Tonton Video' },
            { title: 'Apa itu SDGs?', desc: 'Pelajari tentang Tujuan Pembangunan Berkelanjutan', btn: 'Pelajari Lebih →' },
            { title: 'Jelajahi 17 Tujuan SDGs', desc: 'Telusuri semua tujuan dan targetnya seperti kamus', btn: 'Jelajahi Tujuan →' },
        ],
        sectionTitle: 'Produk Tersedia', sectionSubtitle: '17 Tujuan Pembangunan Berkelanjutan SDGs',
        selectBtn: '🛒 Pilih', selectedBtn: '🛒 Dipilih', quickBtn: '⚡ Langsung Aksi',
        goalLabel: 'Tujuan',
        cartTitle: 'Tujuan SDGs yang Dipilih', backBtn: 'Kembali',
        cartEmpty: 'Belum ada tujuan yang dipilih.', goSelectBtn: 'Pilih Tujuan',
        totalGoals: 'Total Tujuan:', toCheckoutBtn: 'Buat Rencana Aksi',
        selectedGoals: 'Dipilih:', toCheckoutShort: 'Buat Rencana',
        checkoutTitle: 'Buat Rencana Aksi', backToCart: 'Kembali ke Keranjang',
        ordererInfo: 'Informasi Anda',
        nameRequired: 'Nama *', namePlaceholder: 'Masukkan nama Anda',
        schoolRequired: 'Nama Sekolah *', schoolPlaceholder: 'Masukkan nama sekolah',
        gradeRequired: 'Kelas *', gradeSelect: 'Pilih Kelas', gradeOption: n => `Kelas ${n}`,
        classLabel: 'Rombel', classPlaceholder: 'Masukkan rombel',
        deliveryInfo: 'Informasi Pengiriman (Opsional)', deliveryAddress: 'Alamat Pengiriman',
        deliveryAddressPlaceholder: 'Masukkan alamat pengiriman', deliveryMemo: 'Catatan Pengiriman (Opsional)',
        deliveryMemos: ['Pengiriman cepat','Taruh di depan pintu','Beri tahu jika tidak dipraktikkan','Titip ke teman jika tidak ada'],
        orderItems: 'Tujuan yang Dipilih', paymentMethod: 'Metode Aksi',
        paymentMethods: ['🤔 Berpikir','💝 Berempati','🚀 Bertindak'],
        paymentValues: ['think','empathize','action'],
        actionPlanTitle: 'Input Rencana Aksi', planMethodLabel: 'Pilih Metode',
        planMethods: ['Tulis','Gambar','Keduanya'],
        planValues: ['text','drawing','both'],
        myPlanLabel: 'Rencana Aksi Saya',
        planPlaceholder: 'Tuliskan tindakan yang akan Anda lakukan untuk tujuan SDGs yang dipilih.',
        drawingLabel: 'Gambar Rencana Aksi',
        clearCanvas: 'Hapus', colorLabel: 'Warna:', sizeLabel: 'Ukuran:',
        cancelBtn: 'Batal', submitBtn: 'Komitmen',
        errorPayment: 'Pilih setidaknya satu metode aksi.',
        receiptTitle: 'Kuitansi Aksi', downloadBtn: '📥 Unduh Kuitansi',
        printBtn: '🖨️ Cetak', completeBtn: 'Selesai',
        receiptSubtitle: 'Kuitansi Aksi', receiptOrdererInfo: 'Informasi Anda',
        receiptName: 'Nama:', receiptSchool: 'Sekolah:', receiptGrade: 'Kelas/Rombel:',
        receiptGoals: 'Tujuan SDGs yang Dipilih', receiptTotalGoals: 'Total Tujuan:',
        receiptPlanTitle: 'Rencana Aksi Saya', receiptDrawingTitle: 'Gambar Rencana Aksi',
        receiptFooter: 'Kuitansi ini adalah bukti komitmen Anda terhadap SDGs.',
        receiptFooter2: 'Bersama untuk dunia yang lebih baik! 🌍',
        completionTitle: 'Selamat!', completionMsg1: 'Anda telah berkomitmen pada SDGs!',
        completionMsg2: 'Pilihan Anda adalah langkah pertama untuk bumi kita.',
        completionMsg3: 'Aksi kecil bersama membuat perbedaan besar.',
        completionMsg4: 'Mari membangun dunia yang lebih baik, mulai sekarang!',
        homeBtn: 'Kembali ke Beranda',
        toastAddTitle: 'Tujuan Dipilih', toastAddDesc: t => `"${t}" telah ditambahkan!`,
        toastError: 'Kesalahan', toastDownload: 'Unduhan Selesai', toastDownloadDesc: 'Kuitansi berhasil diunduh.',
        toastPrint: 'Siap Cetak', toastPrintDesc: 'Jendela cetak terbuka.',
        toastPrintFail: 'Gagal Mencetak', toastPrintFailDesc: 'Popup diblokir. Harap izinkan popup.',
        footerCredit: 'created by. 교육뮤지컬 꿈꾸는 치수쌤',
        footerNote: 'Website ini hanya untuk tujuan pendidikan SDGs. Tidak ada pembayaran atau pengiriman nyata.',
        countUnit: '',
    },
};

// ── SDG GOAL DATA (multilingual) ─────────────────────────────────────────────
const SDG_DATA = [
    { id:1,  color:'#E5243B', icon:'🏠',
      ko:{title:'빈곤 퇴치', desc:'모든 곳에서 모든 형태의 빈곤 종식',
          targets:['2030년까지 하루 $2.15 미만으로 생활하는 극빈층 완전 종식','모든 사람을 위한 사회적 보호 시스템 구축 및 빈곤층 지원','빈곤층의 자원·기술·금융 서비스 접근성 보장','기후변화 및 경제위기에 대한 취약계층 회복력 강화']},
      en:{title:'No Poverty', desc:'End poverty in all its forms everywhere',
          targets:['End extreme poverty (living on less than $2.15/day) by 2030','Implement social protection systems for everyone','Ensure equal access to economic resources and basic services','Build resilience of the poor against climate-related disasters']},
      ja:{title:'貧困をなくそう', desc:'あらゆる場所のあらゆる形態の貧困を終わらせる'},
      id:{title:'Tanpa Kemiskinan', desc:'Mengakhiri kemiskinan dalam segala bentuknya'} },
    { id:2,  color:'#DDA63A', icon:'🌾',
      ko:{title:'기아 종식', desc:'기아 종식, 식량안보 달성과 지속가능한 농업 강화',
          targets:['2030년까지 기아 종식 및 모든 사람의 식량 안보 달성','모든 형태의 영양실조 종식 (영유아 성장부진 포함)','지속가능한 농업으로 소농의 생산성 및 소득 두 배 향상','씨앗·식물·가축의 유전적 다양성 보전 및 공정한 공유']},
      en:{title:'Zero Hunger', desc:'End hunger, achieve food security and promote sustainable agriculture',
          targets:['End hunger and ensure food security for all by 2030','End all forms of malnutrition, including stunting in children','Double agricultural productivity and incomes of small-scale food producers','Ensure sustainable food production systems and resilient practices']},
      ja:{title:'飢餓をゼロに', desc:'飢餓を終わらせ、食料安全保障と持続可能な農業を促進する'},
      id:{title:'Tanpa Kelaparan', desc:'Mengakhiri kelaparan dan mencapai ketahanan pangan'} },
    { id:3,  color:'#4C9F38', icon:'💚',
      ko:{title:'건강과 웰빙', desc:'모든 연령층을 위한 건강한 삶 보장과 웰빙 증진',
          targets:['모성 사망률을 출생아 10만 명당 70명 미만으로 감소','신생아 및 5세 미만 아동의 예방 가능한 사망 종식','HIV/에이즈·결핵·말라리아 등 전염병 유행 종식','비전염성 질환으로 인한 조기 사망률 1/3 감소','보편적 건강 보장(UHC) 달성 및 의료비 부담 경감']},
      en:{title:'Good Health & Well-being', desc:'Ensure healthy lives and promote well-being for all at all ages',
          targets:['Reduce maternal mortality to below 70 per 100,000 live births','End preventable deaths of newborns and children under 5','End epidemics of AIDS, tuberculosis, malaria, and neglected tropical diseases','Reduce premature mortality from non-communicable diseases by one third','Achieve universal health coverage (UHC)']},
      ja:{title:'すべての人に健康と福祉を', desc:'あらゆる年齢のすべての人の健康な生活を確保する'},
      id:{title:'Kehidupan Sehat dan Sejahtera', desc:'Menjamin kehidupan yang sehat untuk semua usia'} },
    { id:4,  color:'#C5192D', icon:'📚',
      ko:{title:'양질의 교육', desc:'포용적이고 공평한 양질의 교육보장과 평생학습 기회 증진',
          targets:['모든 아동에게 무상 초·중등 교육 보장','양질의 영유아 교육 및 보육 접근성 확대','직업기술교육 및 평생학습 기회 확대','교육 분야의 성별·소득 격차 완전 해소','지속가능발전과 세계시민교육 강화']},
      en:{title:'Quality Education', desc:'Ensure inclusive and equitable quality education and lifelong learning for all',
          targets:['Ensure free, equitable, and quality primary and secondary education for all','Ensure access to quality early childhood development and pre-primary education','Ensure equal access to vocational and higher education for all','Eliminate gender disparities and ensure equal access for the vulnerable','Promote education for sustainable development and global citizenship']},
      ja:{title:'質の高い教育をみんなに', desc:'すべての人に包摂的かつ公正な質の高い教育を確保する'},
      id:{title:'Pendidikan Berkualitas', desc:'Menjamin pendidikan berkualitas untuk semua'} },
    { id:5,  color:'#FF3A21', icon:'⚖️',
      ko:{title:'성평등', desc:'성평등 달성과 모든 여성 및 여아의 권익신장',
          targets:['여성과 여아에 대한 모든 형태의 차별 종식','여성에 대한 폭력·인신매매·성착취 근절','조기 결혼 및 강제 결혼 종식','경제·정치·공공생활에서의 여성 참여 확대','디지털·금융·재산 접근의 성별 격차 해소']},
      en:{title:'Gender Equality', desc:'Achieve gender equality and empower all women and girls',
          targets:['End all forms of discrimination against all women and girls','Eliminate all violence against women and girls, including trafficking','End child, early, and forced marriage','Ensure full and effective participation of women in leadership','Eliminate gender disparities in access to digital, financial and property rights']},
      ja:{title:'ジェンダー平等を実現しよう', desc:'ジェンダー平等を達成し、すべての女性の能力強化を行う'},
      id:{title:'Kesetaraan Gender', desc:'Mencapai kesetaraan gender dan memberdayakan perempuan'} },
    { id:6,  color:'#26BDE2', icon:'💧',
      ko:{title:'깨끗한 물과 위생', desc:'모두를 위한 물과 위생의 이용가능성과 지속가능한 관리 보장',
          targets:['안전하고 저렴한 식수에 대한 보편적 접근 달성','위생시설 및 화장실 접근성 보편화, 노상배변 종식','수질 개선 및 수원 오염·유해물질 방류 감소','물 이용 효율 대폭 향상 및 물 부족 문제 해결','통합 수자원 관리 강화 및 생태계 보호']},
      en:{title:'Clean Water & Sanitation', desc:'Ensure availability and sustainable management of water and sanitation for all',
          targets:['Achieve universal access to safe and affordable drinking water','Achieve access to adequate sanitation and hygiene, end open defecation','Improve water quality by reducing pollution and unsafe discharges','Substantially increase water-use efficiency to address water scarcity','Implement integrated water resources management at all levels']},
      ja:{title:'安全な水とトイレを世界中に', desc:'すべての人々の水と衛生の利用可能性と持続可能な管理を確保する'},
      id:{title:'Air Bersih dan Sanitasi Layak', desc:'Menjamin ketersediaan air bersih dan sanitasi untuk semua'} },
    { id:7,  color:'#FCC30B', icon:'⚡',
      ko:{title:'모두를 위한 깨끗한 에너지', desc:'모두를 위한 적정가격의 신뢰할 수 있는 지속가능한 에너지 접근 보장',
          targets:['현대 에너지 서비스에 대한 보편적 접근 확보','에너지 전체 소비에서 재생에너지 비중 대폭 증가','에너지 효율 개선 속도 두 배 향상','청정에너지 기술의 국제 협력 및 개발도상국 지원 강화']},
      en:{title:'Affordable & Clean Energy', desc:'Ensure access to affordable, reliable, sustainable, and modern energy for all',
          targets:['Ensure universal access to affordable, reliable, and modern energy services','Substantially increase the share of renewable energy','Double the rate of improvement in energy efficiency','Enhance international cooperation to facilitate clean energy research and technology']},
      ja:{title:'エネルギーをみんなにそしてクリーンに', desc:'すべての人に手ごろで信頼できる持続可能な近代的エネルギーへのアクセスを確保する'},
      id:{title:'Energi Bersih dan Terjangkau', desc:'Menjamin akses energi yang terjangkau dan berkelanjutan'} },
    { id:8,  color:'#A21942', icon:'💼',
      ko:{title:'양질의 일자리와 경제성장', desc:'포용적·지속가능한 경제성장, 완전고용과 양질의 일자리 증진',
          targets:['포용적이고 지속가능한 경제 성장 유지','완전하고 생산적인 고용 및 양질의 일자리 증진','청년·여성·장애인 고용 및 직업훈련 확대','강제노동·현대판 노예제·아동노동 근절','모든 노동자의 안전하고 안정적인 근무 환경 보장']},
      en:{title:'Decent Work & Economic Growth', desc:'Promote sustained, inclusive, and sustainable economic growth and decent work for all',
          targets:['Sustain per capita economic growth and higher economic productivity','Achieve full and productive employment and decent work for all','Expand access to financial services for youth, women, and persons with disabilities','End forced labor, modern slavery, human trafficking, and child labor','Protect labour rights and ensure safe and secure working environments']},
      ja:{title:'働きがいも経済成長も', desc:'包摂的かつ持続可能な経済成長と働きがいのある雇用を促進する'},
      id:{title:'Pekerjaan Layak dan Pertumbuhan Ekonomi', desc:'Mendorong pertumbuhan ekonomi inklusif dan berkelanjutan'} },
    { id:9,  color:'#FD6925', icon:'🏭',
      ko:{title:'산업·혁신·사회기반시설', desc:'회복력 있는 인프라 구축, 포용적·지속가능한 산업화 증진과 혁신 도모',
          targets:['지속가능한 교통·에너지·ICT 인프라 개발','중소기업의 금융·기술·시장 접근성 강화','산업 분야의 자원 효율성 향상 및 청정기술 도입','연구개발(R&D) 투자 확대 및 기술 혁신 촉진','ICT 접근성 확대 및 디지털 격차 해소']},
      en:{title:'Industry, Innovation & Infrastructure', desc:'Build resilient infrastructure, promote inclusive and sustainable industrialization, and foster innovation',
          targets:['Develop quality, reliable, sustainable and resilient infrastructure','Promote inclusive and sustainable industrialization','Increase the access of small-scale enterprises to financial services','Upgrade industries to make them sustainable, with greater resource efficiency','Increase access to information and communications technology (ICT)']},
      ja:{title:'産業と技術革新の基盤をつくろう', desc:'強靭なインフラ構築、包摂的かつ持続可能な産業化とイノベーションを推進する'},
      id:{title:'Industri, Inovasi dan Infrastruktur', desc:'Membangun infrastruktur tangguh dan mendorong inovasi'} },
    { id:10, color:'#DD1367', icon:'🟰',
      ko:{title:'불평등 감소', desc:'국내 및 국가 간 불평등 감소',
          targets:['하위 40% 소득 성장률을 국가 평균보다 높게 유지','사회적·경제적·정치적 포용 강화 및 차별 금지','기회 균등 보장 및 불평등한 결과의 점진적 해소','국제 이주민의 안전하고 질서 있는 이동 지원','글로벌 금융 규제 개선 및 개발도상국 발언권 강화']},
      en:{title:'Reduced Inequalities', desc:'Reduce inequality within and among countries',
          targets:['Progressively achieve income growth of the bottom 40% at a rate higher than the national average','Promote the social, economic and political inclusion of all','Ensure equal opportunity and reduce inequalities of outcome','Facilitate orderly, safe, and responsible migration and mobility of people','Enhance global financial regulation and strengthen developing countries voice']},
      ja:{title:'人や国の不平等をなくそう', desc:'各国内及び各国間の不平等を是正する'},
      id:{title:'Berkurangnya Kesenjangan', desc:'Mengurangi kesenjangan intra dan antarnegara'} },
    { id:11, color:'#FD9D24', icon:'🏙️',
      ko:{title:'지속가능한 도시와 공동체', desc:'포용적이고 안전하며 회복력 있고 지속가능한 도시와 주거지 조성',
          targets:['안전하고 저렴한 주거 및 기본 서비스 접근성 보장, 슬럼 개선','안전하고 저렴하며 지속가능한 대중교통 시스템 확대','포용적이고 지속가능한 도시화 및 참여적 도시계획 강화','세계 문화유산 및 자연유산 보호 강화','자연재해 및 기후위기로 인한 도시 피해와 인명피해 대폭 감소']},
      en:{title:'Sustainable Cities & Communities', desc:'Make cities inclusive, safe, resilient, and sustainable',
          targets:['Ensure access for all to adequate and affordable housing and basic services, and upgrade slums','Provide access to safe, affordable, accessible, and sustainable transport systems','Enhance inclusive and sustainable urbanization with participatory planning','Strengthen efforts to protect and safeguard the world\'s cultural and natural heritage','Significantly reduce deaths and economic losses from disasters in cities']},
      ja:{title:'住み続けられるまちづくりを', desc:'包摂的で安全かつ強靭で持続可能な都市を実現する'},
      id:{title:'Kota dan Permukiman yang Berkelanjutan', desc:'Menjadikan kota inklusif, aman, tangguh, dan berkelanjutan'} },
    { id:12, color:'#BF8B2E', icon:'♻️',
      ko:{title:'지속가능한 생산과 소비', desc:'지속가능한 소비와 생산 양식의 보장',
          targets:['지속가능한 소비·생산에 관한 국가별 계획 수립 및 실행','소매·소비자 단계에서의 전 세계 식품 낭비 절반 감소','화학물질 및 유해폐기물의 친환경적 관리 및 방출 감소','폐기물 발생량을 예방·감축·재활용·재사용으로 대폭 감소','지속가능한 관광 정책 및 지속가능한 공공조달 강화']},
      en:{title:'Responsible Consumption & Production', desc:'Ensure sustainable consumption and production patterns',
          targets:['Implement the 10-Year Framework of Programmes on Sustainable Consumption and Production','Halve per capita food waste at the retail and consumer levels by 2030','Achieve environmentally sound management of chemicals and hazardous wastes','Substantially reduce waste generation through prevention, reduction, recycling and reuse','Promote sustainable public procurement practices and sustainable tourism']},
      ja:{title:'つくる責任つかう責任', desc:'持続可能な生産消費形態を確保する'},
      id:{title:'Konsumsi dan Produksi yang Bertanggung Jawab', desc:'Menjamin pola produksi dan konsumsi yang berkelanjutan'} },
    { id:13, color:'#3F7E44', icon:'🌍',
      ko:{title:'기후변화 대응', desc:'기후변화와 그로 인한 영향에 맞서기 위한 긴급 대응',
          targets:['모든 국가의 기후 관련 재해에 대한 회복력 및 적응력 강화','기후변화 대응 정책·전략·계획을 국가 정책에 통합','기후변화 완화·적응·감축에 관한 교육과 인식 제고','개발도상국의 기후 대응 역량 강화 및 지원 확대','녹색기후기금(GCF) 운영 및 1000억 달러 공약 이행']},
      en:{title:'Climate Action', desc:'Take urgent action to combat climate change and its impacts',
          targets:['Strengthen resilience and adaptive capacity to climate-related hazards in all countries','Integrate climate change measures into national policies, strategies and planning','Improve education, awareness-raising and human capacity on climate change','Implement the commitment by developed countries to mobilize climate finance','Promote mechanisms for raising capacity for effective planning in developing countries']},
      ja:{title:'気候変動に具体的な対策を', desc:'気候変動及びその影響を軽減するための緊急対策を講じる'},
      id:{title:'Penanganan Perubahan Iklim', desc:'Mengambil tindakan cepat untuk mengatasi perubahan iklim'} },
    { id:14, color:'#0A97D9', icon:'🐠',
      ko:{title:'해양생태계 보존', desc:'지속가능발전을 위한 대양·바다·해양자원의 보전과 지속가능한 이용',
          targets:['해양 오염(플라스틱·영양과잉 등) 대폭 예방 및 감소','연안·해양 생태계의 지속가능한 방식으로의 보호·복원','불법·비보고·비규제 어업 종식 및 과잉어업 중단','해양 자원의 과학 기반 지속가능한 관리 및 보전','소도서 개발도상국의 해양 자원으로부터 혜택 접근성 증대']},
      en:{title:'Life Below Water', desc:'Conserve and sustainably use the oceans, seas, and marine resources',
          targets:['Prevent and significantly reduce marine pollution of all kinds','Sustainably manage and protect marine and coastal ecosystems','End illegal, unreported and unregulated (IUU) fishing','Regulate harvesting and end overfishing to restore fish stocks','Increase the economic benefits of sustainable use of marine resources for island states']},
      ja:{title:'海の豊かさを守ろう', desc:'海洋・海洋資源を保全し、持続可能な形で利用する'},
      id:{title:'Ekosistem Lautan', desc:'Melestarikan dan memanfaatkan sumber daya kelautan secara berkelanjutan'} },
    { id:15, color:'#56C02B', icon:'🌳',
      ko:{title:'육상생태계 보존', desc:'육상생태계 보호·복원, 지속가능한 산림관리, 사막화 방지, 생물다양성 손실 중단',
          targets:['내륙 담수 생태계 및 육상 생태계의 보전과 복원','산림 황폐화 중단, 훼손된 산림 복원 및 조림 강화','사막화 방지 및 토지 황폐화 중립 달성','산악 생태계 보전 및 산악 생물다양성 강화','야생동식물 불법 거래·밀렵·밀수 종식']},
      en:{title:'Life on Land', desc:'Protect, restore, and promote sustainable use of terrestrial ecosystems and halt biodiversity loss',
          targets:['Ensure the conservation, restoration and sustainable use of terrestrial and freshwater ecosystems','Promote the implementation of sustainable management of all types of forests','Combat desertification, restore degraded land and soil, and achieve land degradation neutrality','Ensure the conservation of mountain ecosystems and their biodiversity','Take urgent action to end poaching and trafficking of protected species']},
      ja:{title:'陸の豊かさも守ろう', desc:'陸域生態系の保護・回復と生物多様性の損失を阻止する'},
      id:{title:'Ekosistem Daratan', desc:'Melindungi ekosistem daratan dan menghentikan kehilangan keanekaragaman hayati'} },
    { id:16, color:'#00689D', icon:'🏛️',
      ko:{title:'정의·평화·효과적인 제도', desc:'평화롭고 포용적인 사회 증진, 정의 보장과 효과적·책임있는 제도 구축',
          targets:['모든 형태의 폭력 및 폭력 관련 사망률 대폭 감소','아동 학대·착취·인신매매 종식','법치주의 강화 및 모든 사람의 사법 접근성 보장','부패 및 뇌물 감소, 투명하고 책임 있는 정부 구축','포용적이고 참여적이며 대표성 있는 의사결정 보장']},
      en:{title:'Peace, Justice & Strong Institutions', desc:'Promote peaceful and inclusive societies, provide access to justice for all',
          targets:['Significantly reduce all forms of violence and related death rates','End abuse, exploitation, trafficking and all forms of violence against children','Promote the rule of law and ensure equal access to justice for all','Substantially reduce corruption and bribery in all their forms','Ensure responsive, inclusive, participatory and representative decision-making']},
      ja:{title:'平和と公正をすべての人に', desc:'平和で包摂的な社会を促進し、すべての人に司法へのアクセスを提供する'},
      id:{title:'Perdamaian, Keadilan dan Kelembagaan yang Tangguh', desc:'Mendorong masyarakat damai dan menyediakan akses keadilan'} },
    { id:17, color:'#19486A', icon:'🤝',
      ko:{title:'글로벌 파트너쉽', desc:'이행수단 강화와 지속가능발전을 위한 글로벌 파트너십 재활성화',
          targets:['개발도상국 세수 및 조세 역량 강화','선진국의 공적개발원조(ODA) 약속 이행 강화','개발도상국의 부채 지속가능성 확보 지원','다자무역 체제 강화 및 개발도상국 무역 장벽 해소','지식·기술·혁신 파트너십 및 데이터·모니터링 역량 강화']},
      en:{title:'Partnerships for the Goals', desc:'Strengthen the means of implementation and revitalize the global partnership',
          targets:['Strengthen domestic resource mobilization and improve tax collection in developing countries','Developed countries to fully implement ODA commitments','Help developing countries attain long-term debt sustainability','Promote a universal, rules-based, non-discriminatory multilateral trading system','Enhance the global partnership for sustainable development through knowledge and technology sharing']},
      ja:{title:'パートナーシップで目標を達成しよう', desc:'持続可能な開発のためのグローバル・パートナーシップを活性化する'},
      id:{title:'Kemitraan untuk Mencapai Tujuan', desc:'Menguatkan kemitraan global untuk pembangunan berkelanjutan'} },
];
